# TCL File Generated by Component Editor 17.0
# Thu Jun 15 17:37:03 JST 2017
# DO NOT MODIFY


# 
# dbussel "dbussel" v1.0
#  2017.06.15.17:37:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dbussel
# 
set_module_property DESCRIPTION ""
set_module_property NAME dbussel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dbussel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fmrv32im_BADMEM_sel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fmrv32im_dbussel.v VERILOG PATH src/fmrv32im_dbussel.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point C_MEM
# 
add_interface C_MEM conduit end
set_interface_property C_MEM associatedClock clock
set_interface_property C_MEM associatedReset ""
set_interface_property C_MEM ENABLED true
set_interface_property C_MEM EXPORT_OF ""
set_interface_property C_MEM PORT_NAME_MAP ""
set_interface_property C_MEM CMSIS_SVD_VARIABLES ""
set_interface_property C_MEM SVD_ADDRESS_GROUP ""

add_interface_port C_MEM C_MEM_ADDR addr Output 32
add_interface_port C_MEM C_MEM_BADMEM_EXCPT excpt Input 1
add_interface_port C_MEM C_MEM_ENA ena Output 1
add_interface_port C_MEM C_MEM_RDATA rdata Input 32
add_interface_port C_MEM C_MEM_WAIT wait Input 1
add_interface_port C_MEM C_MEM_WDATA wdata Output 32
add_interface_port C_MEM C_MEM_WSTB wstb Output 4


# 
# connection point D_MEM
# 
add_interface D_MEM conduit end
set_interface_property D_MEM associatedClock clock
set_interface_property D_MEM associatedReset ""
set_interface_property D_MEM ENABLED true
set_interface_property D_MEM EXPORT_OF ""
set_interface_property D_MEM PORT_NAME_MAP ""
set_interface_property D_MEM CMSIS_SVD_VARIABLES ""
set_interface_property D_MEM SVD_ADDRESS_GROUP ""

add_interface_port D_MEM D_MEM_ADDR addr Input 32
add_interface_port D_MEM D_MEM_BADMEM_EXCPT excpt Output 1
add_interface_port D_MEM D_MEM_ENA ena Input 1
add_interface_port D_MEM D_MEM_RDATA rdata Output 32
add_interface_port D_MEM D_MEM_WAIT wait Output 1
add_interface_port D_MEM D_MEM_WDATA wdata Input 32
add_interface_port D_MEM D_MEM_WSTB wstb Input 4


# 
# connection point PERIPHERAL
# 
add_interface PERIPHERAL conduit end
set_interface_property PERIPHERAL associatedClock clock
set_interface_property PERIPHERAL associatedReset ""
set_interface_property PERIPHERAL ENABLED true
set_interface_property PERIPHERAL EXPORT_OF ""
set_interface_property PERIPHERAL PORT_NAME_MAP ""
set_interface_property PERIPHERAL CMSIS_SVD_VARIABLES ""
set_interface_property PERIPHERAL SVD_ADDRESS_GROUP ""

add_interface_port PERIPHERAL PERIPHERAL_BUS_ADDR addr Output 32
add_interface_port PERIPHERAL PERIPHERAL_BUS_ENA ena Output 1
add_interface_port PERIPHERAL PERIPHERAL_BUS_RDATA rdata Input 32
add_interface_port PERIPHERAL PERIPHERAL_BUS_WAIT wait Input 1
add_interface_port PERIPHERAL PERIPHERAL_BUS_WDATA wdata Output 32
add_interface_port PERIPHERAL PERIPHERAL_BUS_WSTB wstb Output 4


# 
# connection point PLIC
# 
add_interface PLIC conduit end
set_interface_property PLIC associatedClock clock
set_interface_property PLIC associatedReset ""
set_interface_property PLIC ENABLED true
set_interface_property PLIC EXPORT_OF ""
set_interface_property PLIC PORT_NAME_MAP ""
set_interface_property PLIC CMSIS_SVD_VARIABLES ""
set_interface_property PLIC SVD_ADDRESS_GROUP ""

add_interface_port PLIC PLIC_BUS_ADDR addr Output 4
add_interface_port PLIC PLIC_BUS_RDATA rdata Input 32
add_interface_port PLIC PLIC_BUS_WDATA wdata Output 32
add_interface_port PLIC PLIC_BUS_WE we Output 1


# 
# connection point TIMER
# 
add_interface TIMER conduit end
set_interface_property TIMER associatedClock clock
set_interface_property TIMER associatedReset ""
set_interface_property TIMER ENABLED true
set_interface_property TIMER EXPORT_OF ""
set_interface_property TIMER PORT_NAME_MAP ""
set_interface_property TIMER CMSIS_SVD_VARIABLES ""
set_interface_property TIMER SVD_ADDRESS_GROUP ""

add_interface_port TIMER TIMER_BUS_ADDR addr Output 4
add_interface_port TIMER TIMER_BUS_RDATA rdata Input 32
add_interface_port TIMER TIMER_BUS_WDATA wdata Output 32
add_interface_port TIMER TIMER_BUS_WE we Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

