# TCL File Generated by Component Editor 17.0
# Thu Jun 15 17:21:46 JST 2017
# DO NOT MODIFY


# 
# axilm "axilm" v1.0
#  2017.06.15.17:21:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axilm
# 
set_module_property DESCRIPTION ""
set_module_property NAME axilm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axilm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fmrv32im_axilm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fmrv32im_axilm.v VERILOG PATH src/fmrv32im_axilm.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point altera_axi4lite_master
# 
add_interface altera_axi4lite_master axi4lite start
set_interface_property altera_axi4lite_master associatedClock clock
set_interface_property altera_axi4lite_master associatedReset reset
set_interface_property altera_axi4lite_master readIssuingCapability 1
set_interface_property altera_axi4lite_master writeIssuingCapability 1
set_interface_property altera_axi4lite_master combinedIssuingCapability 1
set_interface_property altera_axi4lite_master ENABLED true
set_interface_property altera_axi4lite_master EXPORT_OF ""
set_interface_property altera_axi4lite_master PORT_NAME_MAP ""
set_interface_property altera_axi4lite_master CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_master SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_master M_AXI_ARADDR araddr Output 32
add_interface_port altera_axi4lite_master M_AXI_ARPROT arprot Output 3
add_interface_port altera_axi4lite_master M_AXI_ARREADY arready Input 1
add_interface_port altera_axi4lite_master M_AXI_ARVALID arvalid Output 1
add_interface_port altera_axi4lite_master M_AXI_AWADDR awaddr Output 32
add_interface_port altera_axi4lite_master M_AXI_AWPROT awprot Output 3
add_interface_port altera_axi4lite_master M_AXI_AWREADY awready Input 1
add_interface_port altera_axi4lite_master M_AXI_AWVALID awvalid Output 1
add_interface_port altera_axi4lite_master M_AXI_BREADY bready Output 1
add_interface_port altera_axi4lite_master M_AXI_BRESP bresp Input 2
add_interface_port altera_axi4lite_master M_AXI_BVALID bvalid Input 1
add_interface_port altera_axi4lite_master M_AXI_RDATA rdata Input 32
add_interface_port altera_axi4lite_master M_AXI_RREADY rready Output 1
add_interface_port altera_axi4lite_master M_AXI_RRESP rresp Input 2
add_interface_port altera_axi4lite_master M_AXI_RVALID rvalid Input 1
add_interface_port altera_axi4lite_master M_AXI_WDATA wdata Output 32
add_interface_port altera_axi4lite_master M_AXI_WREADY wready Input 1
add_interface_port altera_axi4lite_master M_AXI_WSTRB wstrb Output 4
add_interface_port altera_axi4lite_master M_AXI_WVALID wvalid Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RST_N reset_n Input 1


# 
# connection point D_BUS
# 
add_interface D_BUS conduit end
set_interface_property D_BUS associatedClock clock
set_interface_property D_BUS associatedReset ""
set_interface_property D_BUS ENABLED true
set_interface_property D_BUS EXPORT_OF ""
set_interface_property D_BUS PORT_NAME_MAP ""
set_interface_property D_BUS CMSIS_SVD_VARIABLES ""
set_interface_property D_BUS SVD_ADDRESS_GROUP ""

add_interface_port D_BUS BUS_WAIT wait Output 1
add_interface_port D_BUS BUS_ENA ena Input 1
add_interface_port D_BUS BUS_WSTB wstb Input 4
add_interface_port D_BUS BUS_ADDR addr Input 32
add_interface_port D_BUS BUS_WDATA wdata Input 32
add_interface_port D_BUS BUS_RDATA rdata Output 32

