# TCL File Generated by Component Editor 17.0
# Thu Jun 15 17:21:02 JST 2017
# DO NOT MODIFY


# 
# fmrv32im "fmrv32im" v1.0
#  2017.06.15.17:21:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fmrv32im
# 
set_module_property DESCRIPTION ""
set_module_property NAME fmrv32im
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fmrv32im
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fmrv32im
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fmrv32im.v VERILOG PATH src/fmrv32im.v TOP_LEVEL_FILE
add_fileset_file fmrv32im_alu.v VERILOG PATH src/fmrv32im_alu.v
add_fileset_file fmrv32im_csr.v VERILOG PATH src/fmrv32im_csr.v
add_fileset_file fmrv32im_decode.v VERILOG PATH src/fmrv32im_decode.v
add_fileset_file fmrv32im_div.v VERILOG PATH src/fmrv32im_div.v
add_fileset_file fmrv32im_mul.v VERILOG PATH src/fmrv32im_mul.v
add_fileset_file fmrv32im_reg.v VERILOG PATH src/fmrv32im_reg.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RST_N reset_n Input 1


# 
# connection point D_MEM
# 
add_interface D_MEM conduit end
set_interface_property D_MEM associatedClock clock
set_interface_property D_MEM associatedReset ""
set_interface_property D_MEM ENABLED true
set_interface_property D_MEM EXPORT_OF ""
set_interface_property D_MEM PORT_NAME_MAP ""
set_interface_property D_MEM CMSIS_SVD_VARIABLES ""
set_interface_property D_MEM SVD_ADDRESS_GROUP ""

add_interface_port D_MEM D_MEM_ADDR addr Output 32
add_interface_port D_MEM D_MEM_BADMEM_EXCPT excpt Input 1
add_interface_port D_MEM D_MEM_ENA ena Output 1
add_interface_port D_MEM D_MEM_RDATA rdata Input 32
add_interface_port D_MEM D_MEM_WAIT wait Input 1
add_interface_port D_MEM D_MEM_WDATA wdata Output 32
add_interface_port D_MEM D_MEM_WSTB wstb Output 4


# 
# connection point I_MEM
# 
add_interface I_MEM conduit end
set_interface_property I_MEM associatedClock clock
set_interface_property I_MEM associatedReset ""
set_interface_property I_MEM ENABLED true
set_interface_property I_MEM EXPORT_OF ""
set_interface_property I_MEM PORT_NAME_MAP ""
set_interface_property I_MEM CMSIS_SVD_VARIABLES ""
set_interface_property I_MEM SVD_ADDRESS_GROUP ""

add_interface_port I_MEM I_MEM_ADDR addr Output 32
add_interface_port I_MEM I_MEM_BADMEM_EXCPT excpt Input 1
add_interface_port I_MEM I_MEM_ENA ena Output 1
add_interface_port I_MEM I_MEM_RDATA rdata Input 32
add_interface_port I_MEM I_MEM_WAIT wait Input 1


# 
# connection point timer_expired
# 
add_interface timer_expired conduit end
set_interface_property timer_expired associatedClock clock
set_interface_property timer_expired associatedReset ""
set_interface_property timer_expired ENABLED true
set_interface_property timer_expired EXPORT_OF ""
set_interface_property timer_expired PORT_NAME_MAP ""
set_interface_property timer_expired CMSIS_SVD_VARIABLES ""
set_interface_property timer_expired SVD_ADDRESS_GROUP ""

add_interface_port timer_expired TIMER_EXPIRED interrupt Input 1


# 
# connection point ext_interrupt
# 
add_interface ext_interrupt conduit end
set_interface_property ext_interrupt associatedClock clock
set_interface_property ext_interrupt associatedReset ""
set_interface_property ext_interrupt ENABLED true
set_interface_property ext_interrupt EXPORT_OF ""
set_interface_property ext_interrupt PORT_NAME_MAP ""
set_interface_property ext_interrupt CMSIS_SVD_VARIABLES ""
set_interface_property ext_interrupt SVD_ADDRESS_GROUP ""

add_interface_port ext_interrupt EXT_INTERRUPT interrupt Input 1

